inherit_from: .hound.suse.yml

AllCops:
  TargetRubyVersion: 2.1
  Rails:
    Enabled: true
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - "crowbar_framework/app/models/chef_node.rb"

Style/RedundantReturn:
Exclude:
  - "chef/data_bags/crowbar/migrate/**/*"

Style/FileName:
  Exclude:
    - "lib/crowbar-*"

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Style/Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500
