#
# Copyright 2011-2013, Dell
# Copyright 2013-2014, SUSE LINUX Products GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source "https://rubygems.org"

gem "rails", "~> 4.2.2"
gem "haml-rails", "~> 0.9.0"
gem "sass-rails", "~> 5.0.3"
gem "puma", "~> 2.11.3"
gem "active_model_serializers", "~> 0.9.0"
gem "uglifier", "~> 2.7.2"
gem "dotenv", "~> 1.0.2"
gem "hashie", "~> 3.4.1"
gem "i18n-js", "~> 2.1.2"
gem "js-routes", "~> 1.0.1"
gem "kwalify", "~> 0.7.2"
gem "simple-navigation", "~> 3.12.2"
gem "simple_navigation_renderers", "~> 1.0.2"
gem "sqlite3", "~> 1.3.9"
gem "syslogger", "~> 1.6.0"
gem "yaml_db", "~> 0.3.0"
gem "easy_diff", "~> 0.0.5"
gem "apipie-rails", "~> 0.3.6"
gem "pg", "~> 0.17.1"

gem "ohai", "~> 6.24.2"
gem "chef", "~> 10.32.2"
gem "net-http-digest_auth", "~> 1.4"

gem "mixlib-shellout", "~> 1.3.0",
    require: "mixlib/shellout"

gem "activerecord-session_store", "~> 0.1.0",
    require: "activerecord/session_store"

if ENV["PACKAGING"] && ENV["PACKAGING"] == "yes"
  gem "mime-types", "~> 2.6.1",
    require: "mime/types"
else
  gem "mime-types", "~> 1.25.0",
    require: "mime/types"
end

gem "activeresource", "~> 4.0.0",
    require: "active_resource"

unless ENV["PACKAGING"] && ENV["PACKAGING"] == "yes"
  group :development do
    gem "byebug", "~> 8.2.2"
    gem "derailed_benchmarks", "~> 1.3.0"
    gem "stackprof", "~> 0.2.8"
  end

  group :test do
    gem "rspec-rails", "~> 3.3.0"
    gem "brakeman", "~> 2.6.3"
    gem "database_cleaner", "~> 1.4.1"
    gem "sinatra", "~> 1.4.5"
    gem "webmock", "~> 1.19.0"
    gem "bundler-audit", "~> 0.4.0"

    gem "cucumber-rails", "~> 1.4.2", require: false
    gem "simplecov", "~> 0.9.1", require: false

    if ENV["CODECLIMATE_REPO_TOKEN"]
      gem "coveralls", require: false
      gem "codeclimate-test-reporter", require: false
    end
  end
end
