#!/bin/bash
# Copyright 2011, Dell
# Copyright 2013-2017, SUSE Linux GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Mark the admin node as ready on reboot.
#

IP="127.0.0.1"

if [[ -f /etc/crowbar.install.key ]]; then
    export CROWBAR_KEY="$(cat /etc/crowbar.install.key)"
    export CROWBAR_PASS="$(sed -e 's/^machine-install://' <<< $CROWBAR_KEY)"
fi

case $1 in
    start|'')
        # clean up files just in case
        rm -rf /var/run/crowbar/looper-chef-client.lock /var/run/crowbar/chef-client.run /var/run/crowbar/chef-client.lock

        # Mark us as readying, and get our cert.
	crowbarctl node transition $HOSTNAME "readying" -U machine-install -P $CROWBAR_PASS --no-verify-ssl
        if [ -f /etc/default/tftpd-hpa ] ; then
          service tftpd-hpa stop
          service tftpd-hpa start
        fi
	crowbarctl node transition $HOSTNAME "ready" -U machine-install -P $CROWBAR_PASS --no-verify-ssl

	echo "Done";;
    stop) bluepill crowbar-webserver stop;;
    status) bluepill crowbar-webserver status;;
    restart) /usr/bin/pumactl -S /opt/dell/crowbar_framework/tmp/pids/puma.state restart;;
    *) echo "Unknown action $1";;
esac
